### ISSUE TITLE
Hilary errors when deploying 10.0

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1114] opened 2015-01-16 15:34 UTC
We should investigate if there is anything we need to fix here.

```
*** OAE Monitoring Alert ***

Notification Type: PROBLEM Host: pp0 State: UP Service output: CRITICAL:566 Hilary errors detected Address: 10.224.14.118 Info: PING OK – Packet loss = 0%, RTA = 1.47 ms

Date/Time: Fri Jan 16 01:15:43 UTC 2015
```

**Comment by nicolaasmatthijs** [comment] 2015-01-16 15:34
Assigning to @simong for investigation

**Comment by simong** [comment] 2015-01-18 15:27
So the errors were all related to the pdf plain text search indexing:
```
[2015-01-16T01:30:59.926Z] ERROR: oae-search/1332 on pp0: Error producing child search documents from resources
    err: {
      "code": 404,
      "msg": "Couldn't find item plain.txt for revisionId: rev:***:*******"
    }
    --
    resources: [
      {
        "id": "c:***:*********"
      }
    ]
```

I'm not entirely sure what's going on though as the revisions I've looked at all had a `plain.txt` file both on the NFS as in the Cassandra DB. FWIW, that errors gets triggered by `getContentPreview` in the ContentPreviewsDAO. I haven't found anything ominous in the app / db logs so far.

**Comment by simong** [comment] 2015-01-21 16:32
Some of these errors can be explained by the NFS not being mounted on the activity nodes. (The ENOENT failures). The above error is caused by something else though as it's on a PP node.

**Comment by nicolaasmatthijs** [comment] 2015-03-02 15:16
@simong : Can you describe the work that remains here?

**Comment by nicolaasmatthijs** [comment] 2015-05-06 14:03
@simong : Can you provide an update in what outstanding work remains here?

**Comment by simong** [comment] 2015-05-06 14:30
I believe this was fixed in https://github.com/oaeproject/Hilary/pull/1103

**Closed by simong** 2015-05-06 14:30 UTC
Labels: To Fix
