### ISSUE TITLE
public document not visable

### ISSUE THREAD

**Issue by davidoae** [oaeproject/Hilary#1275] opened 2016-01-13 13:52 UTC
Hi,
In reference to this document...
https://research.unity.ac/content/rr/EJXscNyue

I did the following steps;
1. I created the document in my library as a private document.
2. I shared it with this *public* group with view access...
https://research.unity.ac/group/rr/71XRQPm9
3. Upon realising that the document was not visible publicly I used "manage access" on the document to set it to public.

People who are members of the group can see the document.
A non-authed user does not see the document in the public group :(
A non-authed user going directly to the document URL can see the page the document is in without error but no content is shown, instead the following appears...
"This document is currently empty"

So I then created a new document within the above group, as a public document...
https://research.unity.ac/content/rr/VyDf4Syug
For non-authed users this is still not visible within the group. (I am quite confused about this as other documents are visible)
However the non-authed users can see the document correctly by going direct to the doc's url.

**Comment by mrvisser** [comment] 2016-01-13 13:57
Hi David, I seem to see both documents fine in the library of the group when anonymous:

![image](https://cloud.githubusercontent.com/assets/102265/12296106/96d722aa-b9d3-11e5-9870-4b7bbc415f6b.png)

**Comment by davidoae** [comment] 2016-01-13 15:00
Should they not appear in recent activity when added?
Sadly I did not look in the group's library at the time.
Also I no longer get the document is empty message, which seems a bit weird as I certainly did previously, as did Jim. Note I created the document some time, maybe an hour, before adding it to the group.
You are right that now the content seems fine.

**Comment by nicolaasmatthijs** [comment] 2016-05-05 07:14
Closing as "Cannot reproduce". Please reopen if you run into this again.

**Closed by nicolaasmatthijs** 2016-05-05 07:14 UTC
