### ISSUE TITLE
Activity stream shows out-of-date profile picture

### ISSUE THREAD

**Issue by sathomas** [oaeproject/Hilary#1189] opened 2015-05-14 12:28 UTC
This may be working as intended, but I noticed that after changing my profile picture, only some of the images in the activity stream use the new thumbnail. (I changed from the official Georgia Tech ID picture to the avatar.)

![screen shot 2015-05-14 at 8 25 52 am](https://cloud.githubusercontent.com/assets/1731910/7631658/0a9a7fec-fa13-11e4-8653-4a6d6f23828d.png)

**Comment by nicolaasmatthijs** [comment] 2015-05-14 14:58
@mrvisser : Is this expected functionality?

**Comment by nicolaasmatthijs** [comment] 2015-05-14 15:04
When testing this locally, it looks like the actor picture is always updated correctly to the latest profile picture. However, pictures within the activity itself (commenter picture, etc.) are not updated correctly.

Is this how it has been implemented?

**Comment by stuartf** [comment] 2015-05-14 16:31
Yes, this is expected behavior. IIRC it's because once something is in the activity stream it can't really be updated.

**Comment by nicolaasmatthijs** [comment] 2015-05-14 16:50
In that case, we can probably go ahead and close this ticket. Whilst this behaviour is not ideal, I can see the performance implications and changing profile picture is hopefully a rare enough event for this not to be a huge problem.

**Closed by nicolaasmatthijs** 2015-05-14 16:50 UTC
Labels: Feedback requested
