### ISSUE TITLE
Email regressions

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1168] opened 2015-04-24 16:05 UTC
- The footer needs to be updated to reflect the new UI footer
- The styling is a bit messed up:

![screen shot 2015-04-24 at 09 01 42](https://cloud.githubusercontent.com/assets/109850/7323073/fda5af30-ea60-11e4-8d2b-f944243a58af.png)

**Comment by nicolaasmatthijs** [comment] 2015-04-24 16:05
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment] 2015-04-24 19:20
@nicolaasmatthijs I submit a fix for the footer issues, but I can't reproduce the template getting messed up, though it happened to me on QA0 as well. I'd like to get the footer updates merged and then see if I can reproduce on QA0 again afterward.

**Comment by mrvisser** [comment] 2015-04-27 13:04
Provided fix for templating issue as part of https://github.com/oaeproject/Hilary/pull/1171

**Closed by mrvisser** 2015-04-27 13:04 UTC
Labels: To Fix
