### ISSUE TITLE
Unread notification counts are no longer correct

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1259] opened 2015-11-11 15:54 UTC
The unread notification counts are no longer correct, which I believe has been the case since the node redis upgrade.

For example, I only had 3 actual unread notifications in the screenshot below. There were some activities where multiple files were added to a folder or a group, and it looked like the count was increased for each of those files individually.

<img width="1790" alt="screen shot 2015-11-11 at 07 37 16" src="https://cloud.githubusercontent.com/assets/109850/11095305/44f2a7d6-8849-11e5-8378-2a694cd1a0a1.png">

**Comment by nicolaasmatthijs** [comment] 2015-11-11 15:54
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment] 2015-11-11 15:55
This is a duplicate of https://github.com/oaeproject/Hilary/issues/1256

Closing in favour of that ticket

**Closed by mrvisser** 2015-11-11 15:55 UTC
Labels: To Fix
