### ISSUE TITLE
Uncaught SyntaxError while loading the pad

### ISSUE THREAD

**Issue by dehourican** [oaeproject/Hilary#1271] opened 2015-12-14 21:43 UTC
We had created the document: https://marist.oaeproject.org/content/marist/VJOFkfdBx
Upon refresh we received this error: An error occurred while loading the pad
Uncaught SyntaxError: Unexpected token } in https://marist.oaeproject.org/etherpad/1/p/g.RESE5iCJ3w68IQ6E$c_marist_VJOFkfdBx (line 2707)

(PS: The correct spelling for the word occurred includes with two "r"s)

**Comment by mrvisser** [comment] 2015-12-14 21:59
Hi @dehourican , it's not exactly clear what the root cause is (was), but I have restarted the affected etherpad server, and it appears to have resolved the issue.

Please note that you will either need to clear your browser cache to see the effect of the change, or in about 15min all caches should invalidate on their own.

Sorry about that, we'll keep an eye on this issue.

**Comment by nicolaasmatthijs** [comment] 2015-12-15 05:12
@mrvisser : Any indications on what caused this issue yet? Also, should this ticket be closed or is further investigation required?

**Comment by mrvisser** [comment] 2015-12-15 16:06
@nicolaasmatthijs I can't find any indications from the logs what happened. Was going to keep this open a while to track if there are more occurrences. I'm fairly indifferent if you want to close it.

**Comment by nicolaasmatthijs** [comment] 2015-12-29 02:07
As we have not received additional reports about this, I'm going to close this issue.

**Closed by nicolaasmatthijs** 2015-12-29 02:07 UTC
